# step 1
scene.set_background_image(img("""
    dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffffffdddd9ddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddfffffffffffffffffffddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddfffdddddddddddddddddddfffdddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddfffdddddddddddddddddddddddddfffddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddffdddddddddddddddddddddddddddddddffddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddffdddddddddddddddddddddddddddddddddddffddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffddddddddddddddddddffdddddddddddddddddddddddddddddddddddddddffddddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddffffffdddddddddddddddffdddddddddddddddddddddddddddddddddddddddddddddffdddddddddddddddffffffdddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddffddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddd
    dddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddd
    ddddddddddddddddddddddddddddddddddddddddddfdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddddddddddddddddddddddddddddddddd
"""))
info.start_countdown(20)
info.set_score(0)

# step 2
myPlayer : Sprite = None
myPlayer = sprites.create(img("""
    . . . . . . . 6 . . . . . . . .
    . . . . . . 8 6 6 . . . 6 8 . .
    . . . e e e 8 8 6 6 . 6 7 8 . .
    . . e 2 2 2 2 e 8 6 6 7 6 . . .
    . e 2 2 4 4 2 7 7 7 7 7 8 6 . .
    . e 2 4 4 2 6 7 7 7 6 7 6 8 8 .
    e 2 4 5 2 2 6 7 7 6 2 7 7 6 . .
    e 2 4 4 2 2 6 7 6 2 2 6 7 7 6 .
    e 2 4 2 2 2 6 6 2 2 2 e 7 7 6 .
    e 2 4 2 2 4 2 2 2 4 2 2 e 7 6 .
    e 2 4 2 2 2 2 2 2 2 2 2 e c 6 .
    e 2 2 2 2 2 2 2 4 e 2 e e c . .
    e e 2 e 2 2 4 2 2 e e e c . . .
    e e e e 2 e 2 2 e e e c . . . .
    e e e 2 e e c e c c c . . . . .
    . c c c c c c c . . . . . . . .
"""), SpriteKind.player)
myPlayer.set_position(0, 128)
myPlayer.set_velocity(50, 0)
myPlayer.set_bounce_on_wall(True)

# step 3
myHoop : Sprite = None
myHoop = sprites.create(img("""
    . . . . . . . . . . . . . . . .
    . . . . . 2 2 2 2 2 2 2 . . . .
    . . . 2 2 . 1 . 1 . 1 . 2 2 . .
    . . 2 . 1 . 1 . 1 . 1 . 1 . 2 .
    . . 2 . 1 . 1 . 1 . 1 . 1 . 2 .
    . 2 1 . 1 . 1 . 1 . 1 . 1 . 1 2
    . 2 1 . 1 . 1 . 1 . 1 . 1 . 1 2
    . 2 . 1 . 1 . 1 . 1 . 1 . 1 . 2
    . 2 1 . . . . . . . . . . . . 2
    . 2 . . . . . . . . . . . . 1 2
    . 2 1 . . . . . . . . . . . . 2
    . 2 . . . . . . . . . . . . 1 2
    . 1 2 . . . . . . . . . . . 2 1
    . 1 2 . . . . . . . . . . . 2 1
    . 1 . 2 2 . . . . . . . 2 2 . 1
    . 1 1 . 1 2 2 2 2 2 2 2 1 . 1 1
"""), SpriteKind.enemy)
myHoop.set_position(80, 15)

# step 4
def on_event_pressed():
    sprites.create_projectile_from_sprite(img("""
        . . . . 4 4 4 f 4 4 4 . . . . .
        . . 4 4 4 4 4 f 4 4 4 4 4 . . .
        . f 4 4 4 4 4 f 4 4 4 4 4 f . .
        . 4 f 4 4 4 4 f 4 4 4 4 f 4 . .
        4 4 f 4 4 4 4 f 4 4 4 4 f 4 4 .
        4 4 4 f 4 4 4 f 4 4 4 f 4 4 4 .
        4 4 4 4 f 4 4 f 4 4 f 4 4 4 4 .
        f f f f f f f f f f f f f f f .
        4 4 4 4 f 4 4 f 4 4 f 4 4 4 4 .
        4 4 4 f 4 4 4 f 4 4 4 f 4 4 4 .
        4 4 4 f 4 4 4 f 4 4 4 f 4 4 4 .
        . 4 f 4 4 4 4 f 4 4 4 4 f 4 . .
        . f 4 4 4 4 4 f 4 4 4 4 4 f . .
        . . 4 4 4 4 4 f 4 4 4 4 4 . . .
        . . . . 4 4 4 f 4 4 4 . . . . .
        . . . . . . . . . . . . . . . .
    """), myPlayer, 0, -100)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_event_pressed)

# step 5
def on_on_overlap(sprite, otherSprite):
    info.change_score_by(1)
    sprite.destroy(effects.fountain)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap)

